export const manufacturers = [
    "Acura",
    "Alfa Romeo",
    "Aston Martin",
    "Audi",
    "Bentley",
    "BMW",
    "Buick",
    "Cadillac",
    "Chevrolet",
    "Chrysler",
    "Citroen",
    "Dodge",
    "Ferrari",
    "Fiat",
    "Ford",
    "GMC",
    "Honda",
    "Hyundai",
    "Infiniti",
    "Jaguar",
    "Jeep",
    "Kia",
    "Lamborghini",
    "Land Rover",
    "Lexus",
    "Lincoln",
    "Maserati",
    "Mazda",
    "McLaren",
    "Mercedes-Benz",
    "MINI",
    "Mitsubishi",
    "Nissan",
    "Porsche",
    "Ram",
    "Rolls-Royce",
    "Subaru",
    "Tesla",
    "Toyota",
    "Volkswagen",
    "Volvo",
  ];
  
  // Generate years dynamically from 2015 to current year + 3
  const currentYear = new Date().getFullYear();
  const startYear = 2015;
  const endYear = currentYear + 3;
  
  export const yearsOfProduction = [
    { title: "Year", value: "" },
    ...Array.from({ length: endYear - startYear + 1 }, (_, i) => {
      const year = startYear + i;
      return { title: year.toString(), value: year.toString() };
    }),
  ];
  
  export const fuels = [
    {
      title: "Fuel Type",
      value: "",
    },
    {
      title: "Gas",
      value: "gas",
    },
    {
      title: "Electricity",
      value: "electricity",
    },
    {
      title: "Hybrid",
      value: "hybrid",
    },
  ];

  export const transmissionTypes = [
    { title: "Transmission", value: "" },
    { title: "Automatic", value: "a" },
    { title: "Manual", value: "m" },
  ];

  export const priceRanges = [
    { title: "Price Range", value: "" },
    { title: "Under $50", value: "0-50" },
    { title: "$50 - $75", value: "50-75" },
    { title: "$75 - $100", value: "75-100" },
    { title: "Over $100", value: "100+" },
  ];

  export const seatOptions = [
    { title: "Seats", value: "" },
    { title: "2 Seats", value: "2" },
    { title: "4 Seats", value: "4" },
    { title: "5 Seats", value: "5" },
    { title: "7+ Seats", value: "7" },
  ];
  
  export const cars = [
    // Honda Models
    {
      city_mpg: 32,
      class: "compact car",
      combination_mpg: 35,
      cylinders: 4,
      displacement: 2.0,
      drive: "fwd",
      fuel_type: "gas",
      highway_mpg: 42,
      make: "Honda",
      model: "Civic",
      transmission: "a",
      year: 2024,
      price_per_day: 45,
      seats: 5,
      color: "Silver",
      image: "Honda Civic.webp",
    },
    {
      city_mpg: 48,
      class: "midsize car",
      combination_mpg: 48,
      cylinders: 4,
      displacement: 2.0,
      drive: "fwd",
      fuel_type: "hybrid",
      highway_mpg: 48,
      make: "Honda",
      model: "Accord Hybrid",
      transmission: "a",
      year: 2024,
      price_per_day: 55,
      seats: 5,
      color: "White",
      image: "Honda Accord Hybrid.webp",
    },
    {
      city_mpg: 28,
      class: "compact SUV",
      combination_mpg: 30,
      cylinders: 4,
      displacement: 1.5,
      drive: "awd",
      fuel_type: "gas",
      highway_mpg: 34,
      make: "Honda",
      model: "CR-V",
      transmission: "a",
      year: 2023,
      price_per_day: 65,
      seats: 5,
      color: "Black",
      image: "Honda CR-V.webp",
    },
    {
      city_mpg: 40,
      class: "compact SUV",
      combination_mpg: 38,
      cylinders: 4,
      displacement: 2.0,
      drive: "awd",
      fuel_type: "hybrid",
      highway_mpg: 35,
      make: "Honda",
      model: "CR-V Hybrid",
      transmission: "a",
      year: 2024,
      price_per_day: 70,
      seats: 5,
      color: "Blue",
      image: "Honda CR-V Hybrid.webp",
    },
    
    // Toyota Models
    {
      city_mpg: 31,
      class: "compact car",
      combination_mpg: 32,
      cylinders: 4,
      displacement: 2.0,
      drive: "fwd",
      fuel_type: "gas",
      highway_mpg: 40,
      make: "Toyota",
      model: "Corolla",
      transmission: "a",
      year: 2024,
      price_per_day: 42,
      seats: 5,
      color: "Red",
      image: "Toyota Corolla.webp",
    },
    {
      city_mpg: 51,
      class: "midsize car",
      combination_mpg: 53,
      cylinders: 4,
      displacement: 2.5,
      drive: "fwd",
      fuel_type: "hybrid",
      highway_mpg: 53,
      make: "Toyota",
      model: "Camry Hybrid",
      transmission: "a",
      year: 2024,
      price_per_day: 58,
      seats: 5,
      color: "Gray",
      image: "Toyota Camry Hybrid.webp",
    },
    {
      city_mpg: 57,
      class: "compact car",
      combination_mpg: 56,
      cylinders: 4,
      displacement: 1.8,
      drive: "fwd",
      fuel_type: "hybrid",
      highway_mpg: 56,
      make: "Toyota",
      model: "Prius",
      transmission: "a",
      year: 2024,
      price_per_day: 50,
      seats: 5,
      color: "Green",
      image: "Toyota Prius.webp",
    },
    {
      city_mpg: 27,
      class: "midsize SUV",
      combination_mpg: 29,
      cylinders: 4,
      displacement: 2.5,
      drive: "awd",
      fuel_type: "gas",
      highway_mpg: 35,
      make: "Toyota",
      model: "RAV4",
      transmission: "a",
      year: 2023,
      price_per_day: 68,
      seats: 5,
      color: "White",
      image: "Toyota RAV4.webp",
    },
    
    // Tesla Models
    {
      city_mpg: 134,
      class: "midsize car",
      combination_mpg: 132,
      cylinders: 0,
      displacement: 0,
      drive: "rwd",
      fuel_type: "electricity",
      highway_mpg: 126,
      make: "Tesla",
      model: "Model 3",
      transmission: "a",
      year: 2024,
      price_per_day: 85,
      seats: 5,
      color: "White",
      image: "Tesla Model 3.webp",
    },
    {
      city_mpg: 120,
      class: "large car",
      combination_mpg: 115,
      cylinders: 0,
      displacement: 0,
      drive: "awd",
      fuel_type: "electricity",
      highway_mpg: 109,
      make: "Tesla",
      model: "Model S",
      transmission: "a",
      year: 2024,
      price_per_day: 120,
      seats: 5,
      color: "Black",
      image: "Tesla Model S.webp",
    },
    {
      city_mpg: 125,
      class: "midsize SUV",
      combination_mpg: 120,
      cylinders: 0,
      displacement: 0,
      drive: "awd",
      fuel_type: "electricity",
      highway_mpg: 112,
      make: "Tesla",
      model: "Model Y",
      transmission: "a",
      year: 2024,
      price_per_day: 95,
      seats: 7,
      color: "Blue",
      image: "Tesla Model Y.webp",
    },
    
    // BMW Models
    {
      city_mpg: 26,
      class: "compact car",
      combination_mpg: 30,
      cylinders: 4,
      displacement: 2.0,
      drive: "rwd",
      fuel_type: "gas",
      highway_mpg: 36,
      make: "BMW",
      model: "3 Series",
      transmission: "a",
      year: 2024,
      price_per_day: 75,
      seats: 5,
      color: "Silver",
      image: "BMW 3 Series.webp",
    },
    {
      city_mpg: 23,
      class: "midsize SUV",
      combination_mpg: 26,
      cylinders: 4,
      displacement: 2.0,
      drive: "awd",
      fuel_type: "gas",
      highway_mpg: 30,
      make: "BMW",
      model: "X3",
      transmission: "a",
      year: 2023,
      price_per_day: 85,
      seats: 5,
      color: "Black",
      image: "BMW X3.webp",
    },
    {
      city_mpg: 113,
      class: "midsize SUV",
      combination_mpg: 109,
      cylinders: 0,
      displacement: 0,
      drive: "awd",
      fuel_type: "electricity",
      highway_mpg: 105,
      make: "BMW",
      model: "iX",
      transmission: "a",
      year: 2024,
      price_per_day: 110,
      seats: 5,
      color: "White",
      image: "BMW iX.webp",
    },
    
    // Mercedes-Benz Models
    {
      city_mpg: 24,
      class: "compact car",
      combination_mpg: 28,
      cylinders: 4,
      displacement: 2.0,
      drive: "fwd",
      fuel_type: "gas",
      highway_mpg: 35,
      make: "Mercedes-Benz",
      model: "A-Class",
      transmission: "a",
      year: 2023,
      price_per_day: 70,
      seats: 5,
      color: "Silver",
      image: "Mercedes-Benz A-Class.webp",
    },
    {
      city_mpg: 21,
      class: "midsize SUV",
      combination_mpg: 25,
      cylinders: 6,
      displacement: 3.0,
      drive: "awd",
      fuel_type: "gas",
      highway_mpg: 28,
      make: "Mercedes-Benz",
      model: "GLE",
      transmission: "a",
      year: 2024,
      price_per_day: 95,
      seats: 7,
      color: "Black",
      image: "Mercedes-Benz GLE.webp",
    },
    
    // Audi Models
    {
      city_mpg: 25,
      class: "compact car",
      combination_mpg: 29,
      cylinders: 4,
      displacement: 2.0,
      drive: "awd",
      fuel_type: "gas",
      highway_mpg: 34,
      make: "Audi",
      model: "A4",
      transmission: "a",
      year: 2024,
      price_per_day: 72,
      seats: 5,
      color: "Gray",
      image: "Audi A4.webp",
    },
    {
      city_mpg: 22,
      class: "compact SUV",
      combination_mpg: 26,
      cylinders: 4,
      displacement: 2.0,
      drive: "awd",
      fuel_type: "gas",
      highway_mpg: 31,
      make: "Audi",
      model: "Q5",
      transmission: "a",
      year: 2023,
      price_per_day: 80,
      seats: 5,
      color: "White",
      image: "Audi Q5.webp",
    },
    
    // Ford Models
    {
      city_mpg: 23,
      class: "midsize car",
      combination_mpg: 26,
      cylinders: 4,
      displacement: 1.5,
      drive: "fwd",
      fuel_type: "gas",
      highway_mpg: 34,
      make: "Ford",
      model: "Fusion",
      transmission: "a",
      year: 2023,
      price_per_day: 48,
      seats: 5,
      color: "Blue",
      image: "Ford Fusion.webp",
    },
    {
      city_mpg: 126,
      class: "midsize SUV",
      combination_mpg: 105,
      cylinders: 0,
      displacement: 0,
      drive: "awd",
      fuel_type: "electricity",
      highway_mpg: 89,
      make: "Ford",
      model: "Mustang Mach-E",
      transmission: "a",
      year: 2024,
      price_per_day: 90,
      seats: 5,
      color: "Red",
      image: "Ford Mustang Mach-E.webp",
    },
    
    // Chevrolet Models
    {
      city_mpg: 29,
      class: "compact car",
      combination_mpg: 32,
      cylinders: 4,
      displacement: 1.4,
      drive: "fwd",
      fuel_type: "gas",
      highway_mpg: 38,
      make: "Chevrolet",
      model: "Malibu",
      transmission: "a",
      year: 2023,
      price_per_day: 46,
      seats: 5,
      color: "Silver",
      image: "Chevrolet Malibu.webp",
    },
    {
      city_mpg: 120,
      class: "compact car",
      combination_mpg: 113,
      cylinders: 0,
      displacement: 0,
      drive: "fwd",
      fuel_type: "electricity",
      highway_mpg: 108,
      make: "Chevrolet",
      model: "Bolt EV",
      transmission: "a",
      year: 2024,
      price_per_day: 55,
      seats: 5,
      color: "Green",
      image: "Chevrolet Bolt EV.webp",
    },
    
    // Nissan Models
    {
      city_mpg: 29,
      class: "compact car",
      combination_mpg: 32,
      cylinders: 4,
      displacement: 2.0,
      drive: "fwd",
      fuel_type: "gas",
      highway_mpg: 39,
      make: "Nissan",
      model: "Altima",
      transmission: "a",
      year: 2023,
      price_per_day: 47,
      seats: 5,
      color: "White",
      image: "Nissan Altima.webp",
    },
    {
      city_mpg: 104,
      class: "compact car",
      combination_mpg: 108,
      cylinders: 0,
      displacement: 0,
      drive: "fwd",
      fuel_type: "electricity",
      highway_mpg: 113,
      make: "Nissan",
      model: "Leaf",
      transmission: "a",
      year: 2024,
      price_per_day: 52,
      seats: 5,
      color: "Blue",
      image: "Nissan Leaf.webp",
    },
    
    // Hyundai Models
    {
      city_mpg: 33,
      class: "compact car",
      combination_mpg: 37,
      cylinders: 4,
      displacement: 2.0,
      drive: "fwd",
      fuel_type: "gas",
      highway_mpg: 41,
      make: "Hyundai",
      model: "Elantra",
      transmission: "a",
      year: 2024,
      price_per_day: 44,
      seats: 5,
      color: "Red",
      image: "Hyundai Elantra.webp",
    },
    {
      city_mpg: 114,
      class: "compact SUV",
      combination_mpg: 104,
      cylinders: 0,
      displacement: 0,
      drive: "awd",
      fuel_type: "electricity",
      highway_mpg: 94,
      make: "Hyundai",
      model: "Kona Electric",
      transmission: "a",
      year: 2024,
      price_per_day: 62,
      seats: 5,
      color: "Orange",
      image: "Hyundai Kona Electric.webp",
    },
  ];

  export const footerLinks = [
    {
      title: "About",
      links: [
        { title: "How it works", url: "/" },
        { title: "Featured", url: "/" },
        { title: "Partnership", url: "/" },
        { title: "Bussiness Relation", url: "/" },
      ],
    },
    {
      title: "Company",
      links: [
        { title: "Events", url: "/" },
        { title: "Blog", url: "/" },
        { title: "Podcast", url: "/" },
        { title: "Invite a friend", url: "/" },
      ],
    },
    {
      title: "Socials",
      links: [
        { title: "Discord", url: "/" },
        { title: "Instagram", url: "/" },
        { title: "Twitter", url: "/" },
        { title: "Facebook", url: "/" },
      ],
    },
  ];